--- #YAML:1.0
name:               Confman
version:            0.04
abstract:           Perl library to interface with Confman 
author:
    - Masahji Stewart <masahji@synctree.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:          0
    REST::Client:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
